services:
  rowboat:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
        - .env
  jobs-worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
